# Generated by Django 4.2.7 on 2025-08-24 13:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message='Formato de telefone inválido. Use formatos como: (11) 99999-9999, +55 11 99999-9999, etc.', regex='^(\\+?\\d{1,3}[\\s\\-]?)?\\(?\\d{2,3}\\)?[\\s\\-]?\\d{4,5}[\\s\\-]?\\d{4}$')], verbose_name='Telefone'),
        ),
    ]
