# Generated by Django 4.2.7 on 2025-09-16 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_is_temporary',
            field=models.BooleanField(default=False, help_text='Indica se a senha atual é temporária e deve ser alterada no próximo login', verbose_name='Senha Temporária'),
        ),
    ]
